version: "3.9"
services:
  app:
    build: ./infra/php
    user: "${UID}:${GID}"
    volumes:
      - ./backend:/work
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
  web:
    image: nginx:1.20-alpine
    ports:
      - 8080:80
    volumes:
      - ./backend:/work
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /work

  db:
    build: ./infra/mysql
    volumes:
      - ./db:/var/lib/mysql
      
volumes:
  db-store:
